CREATE TABLE IF NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    ttl VARCHAR(255) NOT NULL,
    alamat VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    foto_path VARCHAR(255) NOT NULL,
    createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);