ALTER TABLE students
ADD COLUMN kota VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN provinsi VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN kode_pos INT NOT NULL DEFAULT 0,
ADD COLUMN nomor_hp INT NOT NULL DEFAULT 0,
ADD COLUMN warganegara VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN no_anggota VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN status_mahasiswa BOOlEAN NOT NULL DEFAULT FALSE,
ADD COLUMN lembaga_pendidikan VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN jurusan VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN fakultas VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN bidang_usaha VARCHAR(100) NOT NULL DEFAULT 'none',
ADD COLUMN alamat_usaha VARCHAR(100) NOT NULL DEFAULT 'none';
