ALTER TABLE students
ADD COLUMN kota VARCHAR(100) NOT NULL,
ADD COLUMN provinsi VARCHAR(100) NOT NULL,
ADD COLUMN kode_pos INT NOT NULL,
ADD COLUMN nomor_hp INT NOT NULL,
ADD COLUMN warganegara VARCHAR(100) NOT NULL,
ADD COLUMN no_anggota VARCHAR(100) NOT NULL,
ADD COLUMN status_mahasiswa BOOlEAN NOT NULL,
ADD COLUMN lembaga_pendidikan VARCHAR(100) NOT NULL,
ADD COLUMN jurusan VARCHAR(100) NOT NULL,
ADD COLUMN fakultas VARCHAR(100) NOT NULL,
ADD COLUMN bidang_usaha VARCHAR(100) NOT NULL,
ADD COLUMN alamat_usaha VARCHAR(100) NOT NULL;
